enum QueryKeys {
  POSTS = "POSTS",
  POST_DETAILS = "POST_DETAILS",
  SEARCH = "SEARCH",
  HAS_SEEN_ONBOARDING = "HAS_SEEN_ONBOARDING",
  SEARCH_HASHTAGS = "SEARCH_HASHTAGS",
  HASHTAGS_AND_COUNTER = "HASHTAGS_AND_COUNTER",
  HASHTAG_VIEWER = "HASHTAG_VIEWER",
  GET_USER_PHOTOS = "GET_USER_PHOTOS",
  GET_USER_AVATAR = "GET_USER_AVATAR",
  PICK_AVATAR_PHOTO = "PICK_AVATAR_PHOTO",
  TOTAL_OF_POSTS = "TOTAL_OF_POSTS",
  TOTAL_OF_HASHTAGS = "TOTAL_OF_HASHTAGS",
  IS_DEVELOPER = "IS_DEVELOPER",
  PREFERRED_COLOR_SCHEME = "PREFERRED_COLOR_SCHEME",
  PREFERRED_ACCENT_COLOR = "PREFERRED_ACCENT_COLOR",
}

export { QueryKeys };
