enum QueryKeys {
  POSTS = "POSTS",
  POST_DETAILS = "POST_DETAILS",
  SEARCH = "SEARCH",
  HAS_SEEN_ONBOARDING = "HAS_SEEN_ONBOARDING",
  TOP_HASHTAGS = "TOP_HASHTAGS",
  HASHTAG_VIEWER = "HASHTAG_VIEWER",
  FLUSH_POSTS = "FLUSH_POSTS",
  FLUSH_HASHTAGS = "FLUSH_HASHTAGS",
  GET_USER_PHOTOS = "GET_USER_PHOTOS",
  GET_USER_AVATAR = "GET_USER_AVATAR",
  PICK_AVATAR_PHOTO = "PICK_AVATAR_PHOTO",
  TOTAL_OF_POSTS = "TOTAL_OF_POSTS",
  TOTAL_OF_HASHTAGS = "TOTAL_OF_HASHTAGS",
}

export { QueryKeys };
